name: libsbn
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
  - etetoolkit
dependencies:
  - python=3.7
  - bison=3.4
  - flex
  - make
  - numpy
  - pandas
  - pip
  - pybind11 >=2.3.0
  - pytest
  - scons
  - scipy
  - sphinx >= 2.2.1
  - biopython 
  - ete3
  - seaborn
  - jupyter
  - pip:
      - black
      - click
      - docformatter
      - enscons
      - flake8
      - sphinx-click
      - sphinx-rtd-theme
      - tf-nightly
      - tfp-nightly
